package View;

import Bean.DanhMucBean;
import Controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NHALINH
 */
public class MainFrame_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form NHANVIEN
     */
    public MainFrame_VIEW() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("QUẢN LÍ CỬA HÀNG QUẦN ÁO");

        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);

        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("NHÂN VIÊN", jpnNHANVIEN, jlbNHANVIEN));
        listItem.add(new DanhMucBean("KHÁCH HÀNG", jpnKHACHHANG, jlbKHACHHANG));
        listItem.add(new DanhMucBean("SẢN PHẨM", jpnSANPHAM, jlbSANPHAM));
        listItem.add(new DanhMucBean("HÓA ĐƠN", jpnHOADON, jlbHOADON));
        listItem.add(new DanhMucBean("NHẬP HÀNG", jpnNHAPHANG, jlbNHAPHANG));
        listItem.add(new DanhMucBean("NHÀ CUNG CẤP", jpnNHACUNGCAP, jlbNHACUNGCAP));
        listItem.add(new DanhMucBean("KHUYẾN MÃI", jpnKHUYENMAI, jlbKHUYENMAI));
        listItem.add(new DanhMucBean("THỐNG KÊ", jpnTHONGKE, jlbTHONGKE));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpnMenu = new javax.swing.JPanel();
        jpnNHANVIEN = new javax.swing.JPanel();
        jlbNHANVIEN = new javax.swing.JLabel();
        jpnKHACHHANG = new javax.swing.JPanel();
        jlbKHACHHANG = new javax.swing.JLabel();
        jpnSANPHAM = new javax.swing.JPanel();
        jlbSANPHAM = new javax.swing.JLabel();
        jpnHOADON = new javax.swing.JPanel();
        jlbHOADON = new javax.swing.JLabel();
        jpnNHAPHANG = new javax.swing.JPanel();
        jlbNHAPHANG = new javax.swing.JLabel();
        jpnNHACUNGCAP = new javax.swing.JPanel();
        jlbNHACUNGCAP = new javax.swing.JLabel();
        jpnKHUYENMAI = new javax.swing.JPanel();
        jlbKHUYENMAI = new javax.swing.JLabel();
        jpnTHONGKE = new javax.swing.JPanel();
        jlbTHONGKE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnView.setBackground(new java.awt.Color(255, 200, 231));
        jpnView.setPreferredSize(new java.awt.Dimension(1500, 725));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(205, 104, 108));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME ");
        jLabel4.setMinimumSize(null);
        jLabel4.setPreferredSize(null);

        jLabel3.setBackground(new java.awt.Color(49, 49, 49));
        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(205, 104, 108));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TO");

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 45)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(205, 104, 108));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4L");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(205, 104, 108));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STORE");
        jLabel5.setMinimumSize(null);
        jLabel5.setPreferredSize(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Screenshot (659).png"))); // NOI18N

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnMenu.setBackground(new java.awt.Color(255, 200, 231));

        jpnNHANVIEN.setBackground(new java.awt.Color(255, 200, 231));
        jpnNHANVIEN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbNHANVIEN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbNHANVIEN.setText("NHÂN VIÊN");

        javax.swing.GroupLayout jpnNHANVIENLayout = new javax.swing.GroupLayout(jpnNHANVIEN);
        jpnNHANVIEN.setLayout(jpnNHANVIENLayout);
        jpnNHANVIENLayout.setHorizontalGroup(
            jpnNHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNHANVIENLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlbNHANVIEN)
                .addGap(40, 40, 40))
        );
        jpnNHANVIENLayout.setVerticalGroup(
            jpnNHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNHANVIENLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbNHANVIEN)
                .addGap(18, 18, 18))
        );

        jpnKHACHHANG.setBackground(new java.awt.Color(255, 200, 231));
        jpnKHACHHANG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbKHACHHANG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbKHACHHANG.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout jpnKHACHHANGLayout = new javax.swing.GroupLayout(jpnKHACHHANG);
        jpnKHACHHANG.setLayout(jpnKHACHHANGLayout);
        jpnKHACHHANGLayout.setHorizontalGroup(
            jpnKHACHHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHACHHANGLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbKHACHHANG)
                .addGap(30, 30, 30))
        );
        jpnKHACHHANGLayout.setVerticalGroup(
            jpnKHACHHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHACHHANGLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbKHACHHANG)
                .addGap(18, 18, 18))
        );

        jpnSANPHAM.setBackground(new java.awt.Color(255, 200, 231));
        jpnSANPHAM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbSANPHAM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbSANPHAM.setText("SẢN PHẨM");

        javax.swing.GroupLayout jpnSANPHAMLayout = new javax.swing.GroupLayout(jpnSANPHAM);
        jpnSANPHAM.setLayout(jpnSANPHAMLayout);
        jpnSANPHAMLayout.setHorizontalGroup(
            jpnSANPHAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSANPHAMLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlbSANPHAM)
                .addGap(42, 42, 42))
        );
        jpnSANPHAMLayout.setVerticalGroup(
            jpnSANPHAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSANPHAMLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbSANPHAM)
                .addGap(18, 18, 18))
        );

        jpnHOADON.setBackground(new java.awt.Color(255, 200, 231));
        jpnHOADON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbHOADON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbHOADON.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jpnHOADONLayout = new javax.swing.GroupLayout(jpnHOADON);
        jpnHOADON.setLayout(jpnHOADONLayout);
        jpnHOADONLayout.setHorizontalGroup(
            jpnHOADONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHOADONLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlbHOADON)
                .addGap(46, 46, 46))
        );
        jpnHOADONLayout.setVerticalGroup(
            jpnHOADONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHOADONLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbHOADON)
                .addGap(18, 18, 18))
        );

        jpnNHAPHANG.setBackground(new java.awt.Color(255, 200, 231));
        jpnNHAPHANG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbNHAPHANG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbNHAPHANG.setText("NHẬP HÀNG");

        javax.swing.GroupLayout jpnNHAPHANGLayout = new javax.swing.GroupLayout(jpnNHAPHANG);
        jpnNHAPHANG.setLayout(jpnNHAPHANGLayout);
        jpnNHAPHANGLayout.setHorizontalGroup(
            jpnNHAPHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNHAPHANGLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jlbNHAPHANG)
                .addGap(36, 36, 36))
        );
        jpnNHAPHANGLayout.setVerticalGroup(
            jpnNHAPHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNHAPHANGLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbNHAPHANG)
                .addGap(18, 18, 18))
        );

        jpnNHACUNGCAP.setBackground(new java.awt.Color(255, 200, 231));
        jpnNHACUNGCAP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbNHACUNGCAP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbNHACUNGCAP.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout jpnNHACUNGCAPLayout = new javax.swing.GroupLayout(jpnNHACUNGCAP);
        jpnNHACUNGCAP.setLayout(jpnNHACUNGCAPLayout);
        jpnNHACUNGCAPLayout.setHorizontalGroup(
            jpnNHACUNGCAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNHACUNGCAPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlbNHACUNGCAP)
                .addGap(27, 27, 27))
        );
        jpnNHACUNGCAPLayout.setVerticalGroup(
            jpnNHACUNGCAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNHACUNGCAPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbNHACUNGCAP)
                .addGap(18, 18, 18))
        );

        jpnKHUYENMAI.setBackground(new java.awt.Color(255, 200, 231));
        jpnKHUYENMAI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbKHUYENMAI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbKHUYENMAI.setText("KHUYẾN MÃI");

        javax.swing.GroupLayout jpnKHUYENMAILayout = new javax.swing.GroupLayout(jpnKHUYENMAI);
        jpnKHUYENMAI.setLayout(jpnKHUYENMAILayout);
        jpnKHUYENMAILayout.setHorizontalGroup(
            jpnKHUYENMAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHUYENMAILayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jlbKHUYENMAI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKHUYENMAILayout.setVerticalGroup(
            jpnKHUYENMAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHUYENMAILayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbKHUYENMAI)
                .addGap(18, 18, 18))
        );

        jpnTHONGKE.setBackground(new java.awt.Color(255, 200, 231));
        jpnTHONGKE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbTHONGKE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbTHONGKE.setText("THỐNG KÊ");

        javax.swing.GroupLayout jpnTHONGKELayout = new javax.swing.GroupLayout(jpnTHONGKE);
        jpnTHONGKE.setLayout(jpnTHONGKELayout);
        jpnTHONGKELayout.setHorizontalGroup(
            jpnTHONGKELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTHONGKELayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlbTHONGKE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTHONGKELayout.setVerticalGroup(
            jpnTHONGKELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTHONGKELayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbTHONGKE)
                .addGap(18, 18, 18))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/4L STORE (2).png"))); // NOI18N
        jLabel1.setText("icon");

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnNHANVIEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnKHACHHANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnSANPHAM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnHOADON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnNHAPHANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnNHACUNGCAP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnKHUYENMAI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnTHONGKE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnNHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnKHACHHANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnSANPHAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnHOADON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnNHAPHANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnNHACUNGCAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnKHUYENMAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnTHONGKE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlbHOADON;
    private javax.swing.JLabel jlbKHACHHANG;
    private javax.swing.JLabel jlbKHUYENMAI;
    private javax.swing.JLabel jlbNHACUNGCAP;
    private javax.swing.JLabel jlbNHANVIEN;
    private javax.swing.JLabel jlbNHAPHANG;
    private javax.swing.JLabel jlbSANPHAM;
    private javax.swing.JLabel jlbTHONGKE;
    private javax.swing.JPanel jpnHOADON;
    private javax.swing.JPanel jpnKHACHHANG;
    private javax.swing.JPanel jpnKHUYENMAI;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNHACUNGCAP;
    private javax.swing.JPanel jpnNHANVIEN;
    private javax.swing.JPanel jpnNHAPHANG;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnSANPHAM;
    private javax.swing.JPanel jpnTHONGKE;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
