/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import BUS.NhanVienBUS;
import Model.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileOutputStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author Quang Long
 */
public class NHANVIEN_VIEW extends javax.swing.JPanel {

    DefaultTableModel tableModel;

    /**
     * Creates new form NHANVIEN1
     */
    public NHANVIEN_VIEW() {
        initComponents();

        tableModel = (DefaultTableModel) jtbNHANVIEN.getModel();
        showNHANVIEN();

        jtfTIMKIEMNANGCAO.setEnabled(false);
    }

    public void showNHANVIEN() {

        NhanVienBUS nvBUS = new NhanVienBUS();
        NhanVienBUS.NHANVIENLIST = nvBUS.getAllUsers();

        tableModel.setRowCount(0);
        // Kiểu dữ liệu : biến : Phạm vi truy cập 
        for (NHANVIEN nv : NhanVienBUS.NHANVIENLIST) {
            Vector<String> row = new Vector<>();
            row.add(nv.getMaNV());
            row.add(nv.getTenNV());
            row.add(nv.getSDT_NV());
            row.add(nv.getNgaySinh_NV());
            row.add(nv.getDiaChi_NV());
            tableModel.addRow(row);
        }

        jtbNHANVIEN.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfMANV = new javax.swing.JTextField();
        jtfTENNV = new javax.swing.JTextField();
        jtfSDT_NV = new javax.swing.JTextField();
        jtfNGAYSINH_NV = new javax.swing.JTextField();
        jtfDIACHI_NV = new javax.swing.JTextField();
        btnTHEM = new javax.swing.JButton();
        btnXOA = new javax.swing.JButton();
        btnSUA = new javax.swing.JButton();
        btnRESET = new javax.swing.JButton();
        btnXUAT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbNHANVIEN = new javax.swing.JTable();
        jcbTIMKIEM = new javax.swing.JComboBox<>();
        jtfTIMKIEM = new javax.swing.JTextField();
        jtfTIMKIEMNANGCAO = new javax.swing.JTextField();
        btnTIMKIEM = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 145, 188));
        setPreferredSize(new java.awt.Dimension(1500, 725));

        jpnView.setBackground(new java.awt.Color(210, 145, 188));
        jpnView.setPreferredSize(new java.awt.Dimension(592, 532));

        jPanel14.setBackground(new java.awt.Color(255, 200, 231));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("THÔNG TIN QUẢN LÝ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("ID Nhân viên:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Tên nhân viên:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Số điện thoại:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Năm sinh:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Địa chỉ:");

        jtfMANV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMANVActionPerformed(evt);
            }
        });

        btnTHEM.setBackground(new java.awt.Color(255, 200, 231));
        btnTHEM.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/plus-sign.png"))); // NOI18N
        btnTHEM.setText("THÊM");
        btnTHEM.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTHEM.setMaximumSize(new java.awt.Dimension(577, 521));
        btnTHEM.setPreferredSize(new java.awt.Dimension(577, 521));
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        btnXOA.setBackground(new java.awt.Color(255, 200, 231));
        btnXOA.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete-button.png"))); // NOI18N
        btnXOA.setText("XÓA");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnSUA.setBackground(new java.awt.Color(255, 200, 231));
        btnSUA.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/eraser.png"))); // NOI18N
        btnSUA.setText("SỬA");
        btnSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUAActionPerformed(evt);
            }
        });

        btnRESET.setBackground(new java.awt.Color(255, 200, 231));
        btnRESET.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnRESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.png"))); // NOI18N
        btnRESET.setText("RESET");
        btnRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRESETActionPerformed(evt);
            }
        });

        btnXUAT.setBackground(new java.awt.Color(255, 200, 231));
        btnXUAT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/click.png"))); // NOI18N
        btnXUAT.setText("XUẤT FILE");
        btnXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXUATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfTENNV)
                                .addComponent(jtfSDT_NV)
                                .addComponent(jtfNGAYSINH_NV)
                                .addComponent(jtfDIACHI_NV)))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btnTHEM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btnXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btnSUA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btnRESET, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addComponent(btnXUAT)
                .addGap(334, 334, 334))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(610, 610, 610))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSDT_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNGAYSINH_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDIACHI_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(41, 41, 41)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRESET)
                    .addComponent(btnSUA)
                    .addComponent(btnXOA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTHEM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXUAT))
                .addGap(37, 37, 37))
        );

        jPanel1.setBackground(new java.awt.Color(254, 200, 216));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/teamwork.png"))); // NOI18N
        jLabel11.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(527, 527, 527))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 200, 231));

        jtbNHANVIEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID NV", "Tên NV", "SĐT", "Năm sinh", "Địa chỉ"
            }
        ));
        jtbNHANVIEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbNHANVIENMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbNHANVIEN);

        jcbTIMKIEM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc Định", "Mã NV", "Tên NV", "Ngày Sinh", "Địa chỉ", "Địa Chỉ và Ngày Sinh", "Địa chỉ hoặc Ngày Sinh" }));
        jcbTIMKIEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIMKIEMActionPerformed(evt);
            }
        });

        jtfTIMKIEM.setText("Nhập dữ liệu tìm kiếm");
        jtfTIMKIEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfTIMKIEMMouseClicked(evt);
            }
        });

        jtfTIMKIEMNANGCAO.setText("Nhập dữ liệu tìm kiếm");
        jtfTIMKIEMNANGCAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfTIMKIEMNANGCAOMouseClicked(evt);
            }
        });

        btnTIMKIEM.setBackground(new java.awt.Color(255, 200, 231));
        btnTIMKIEM.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnTIMKIEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/web-search-engine.png"))); // NOI18N
        btnTIMKIEM.setText("Tìm Kiếm");
        btnTIMKIEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTIMKIEMActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/file.png"))); // NOI18N
        jLabel16.setText("THÔNG TIN QUẢN LÝ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTIMKIEMNANGCAO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTIMKIEM)
                .addGap(218, 218, 218))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTIMKIEMNANGCAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTIMKIEM)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewLayout.createSequentialGroup()
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnViewLayout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMANVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMANVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMANVActionPerformed

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        int ktra = 1; //đúng
        NhanVienBUS nvBUS = new NhanVienBUS();
        NHANVIEN nv = new NHANVIEN();
        
        nv.setMaNV(jtfMANV.getText());
        if (jtfMANV.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lỗi không được để Mã NV trống", "Lôi", JOptionPane.ERROR_MESSAGE);
        } else {
            for (NHANVIEN manv : NhanVienBUS.NHANVIENLIST) {
                if (nv.getMaNV().equalsIgnoreCase(manv.getMaNV())) {
                    ktra = 0; //sai
                }
            }
            if (ktra == 1) {

                nv.setTenNV(jtfTENNV.getText());
                nv.setSDT_NV(jtfSDT_NV.getText());
                nv.setNgaySinh_NV(jtfNGAYSINH_NV.getText());
                nv.setDiaChi_NV(jtfDIACHI_NV.getText());

                //NhanVienDAO.insert(nv);
                try {
                    int result = nvBUS.insertUser(nv);
                    if (result != 0) {
                        JOptionPane.showMessageDialog(this,
                                "Thêm dữ liệu thành công!", "Thông báo",
                                JOptionPane.INFORMATION_MESSAGE);
                    }
                    showNHANVIEN();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mã NV đã bị trùng lặp do khởi tạo trước đó", "Lôi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        NhanVienBUS nvBUS = new NhanVienBUS();
        int selectedIndex = jtbNHANVIEN.getSelectedRow();
        if (selectedIndex >= 0) {
            NHANVIEN std = NhanVienBUS.NHANVIENLIST.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");

            if (option == 0) {
                nvBUS.deleteUser(std.getMaNV());

                showNHANVIEN();
            }
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void btnRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRESETActionPerformed
        jtfMANV.setText("");
        jtfTENNV.setText("");
        jtfNGAYSINH_NV.setText("");
        jtfSDT_NV.setText("");
        jtfDIACHI_NV.setText("");
    }//GEN-LAST:event_btnRESETActionPerformed

    private void btnSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUAActionPerformed
        int i = jtbNHANVIEN.getSelectedRow();
        if (i >= 0) {
            NHANVIEN nvold = new NHANVIEN();
            NHANVIEN nv = new NHANVIEN();
            NhanVienBUS nvBUS = new NhanVienBUS();
            nvold = NhanVienBUS.NHANVIENLIST.set(i, nv);

            nv.setMaNV(jtfMANV.getText());
            nv.setTenNV(jtfTENNV.getText());
            nv.setNgaySinh_NV(jtfNGAYSINH_NV.getText());
            nv.setSDT_NV(jtfSDT_NV.getText());
            nv.setDiaChi_NV(jtfDIACHI_NV.getText());

            int result = nvBUS.updateUser(nv, nvold);
            if (result == 1) {
                JOptionPane.showMessageDialog(this,
                        "Cập nhật dữ liệu thành công!", "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
                showNHANVIEN();

            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_btnSUAActionPerformed

    private void btnTIMKIEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTIMKIEMActionPerformed
        String ValueOfFind = jtfTIMKIEM.getText();
        String ValueOFFind_NangCao = jtfTIMKIEMNANGCAO.getText();

        List<NHANVIEN> kq = new ArrayList<>();
        NHANVIEN nv = new NHANVIEN();
        NhanVienBUS nvBUS = new NhanVienBUS();
        int pos = jcbTIMKIEM.getSelectedIndex();
        switch (pos) {
            case 0:
                jtfTIMKIEM.setText("Nhập dữ liệu tìm kiếm");
                jtfTIMKIEMNANGCAO.setText("Nhập dữ liệu tìm kiếm");
                showNHANVIEN();
                break;
            case 1:

                nv = nvBUS.timTheoMa(ValueOfFind);
                if (nv == null) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);

                    Vector<String> row = new Vector<>();
                    row.add(nv.getMaNV());
                    row.add(nv.getTenNV());
                    row.add(nv.getSDT_NV());
                    row.add(nv.getNgaySinh_NV());
                    row.add(nv.getDiaChi_NV());
                    tableModel.addRow(row);

                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            case 2:

                kq = nvBUS.timTheoTen(ValueOfFind);
                if (kq.size() == 0) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);
                    for (NHANVIEN nhanvienkq : kq) {
                        Vector<String> row = new Vector<>();
                        row.add(nhanvienkq.getMaNV());
                        row.add(nhanvienkq.getTenNV());
                        row.add(nhanvienkq.getSDT_NV());
                        row.add(nhanvienkq.getNgaySinh_NV());
                        row.add(nhanvienkq.getDiaChi_NV());
                        tableModel.addRow(row);
                    }
                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            case 3:
                kq = nvBUS.timTheoNamSinh(ValueOfFind);
                if (kq.size() == 0) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);
                    for (NHANVIEN nhanvienkq : kq) {
                        Vector<String> row = new Vector<>();
                        row.add(nhanvienkq.getMaNV());
                        row.add(nhanvienkq.getTenNV());
                        row.add(nhanvienkq.getSDT_NV());
                        row.add(nhanvienkq.getNgaySinh_NV());
                        row.add(nhanvienkq.getDiaChi_NV());
                        tableModel.addRow(row);
                    }
                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            case 4:
                kq = nvBUS.timTheoDiaChi(ValueOfFind);
                if (kq.size() == 0) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);
                    for (NHANVIEN nhanvienkq : kq) {
                        Vector<String> row = new Vector<>();
                        row.add(nhanvienkq.getMaNV());
                        row.add(nhanvienkq.getTenNV());
                        row.add(nhanvienkq.getSDT_NV());
                        row.add(nhanvienkq.getNgaySinh_NV());
                        row.add(nhanvienkq.getDiaChi_NV());
                        tableModel.addRow(row);
                    }
                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            case 5:
                kq = nvBUS.timTheoDiaChivaNgaySinh(ValueOfFind, ValueOFFind_NangCao);
                if (kq.size() == 0) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);
                    for (NHANVIEN nhanvienkq : kq) {
                        Vector<String> row = new Vector<>();
                        row.add(nhanvienkq.getMaNV());
                        row.add(nhanvienkq.getTenNV());
                        row.add(nhanvienkq.getSDT_NV());
                        row.add(nhanvienkq.getNgaySinh_NV());
                        row.add(nhanvienkq.getDiaChi_NV());
                        tableModel.addRow(row);
                    }
                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            case 6:
                kq = nvBUS.timTheoDiaChihoacNgaySinh(ValueOfFind);
                if (kq.size() == 0) {
                    JOptionPane.showMessageDialog(this, "lỗi");
                } else {
                    tableModel.setRowCount(0);
                    for (NHANVIEN nhanvienkq : kq) {
                        Vector<String> row = new Vector<>();
                        row.add(nhanvienkq.getMaNV());
                        row.add(nhanvienkq.getTenNV());
                        row.add(nhanvienkq.getSDT_NV());
                        row.add(nhanvienkq.getNgaySinh_NV());
                        row.add(nhanvienkq.getDiaChi_NV());
                        tableModel.addRow(row);
                    }
                    jtbNHANVIEN.setModel(tableModel);
                }
                break;

            default:
                return;
        }

    }//GEN-LAST:event_btnTIMKIEMActionPerformed

    private void jtfTIMKIEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfTIMKIEMMouseClicked
        jtfTIMKIEM.setText("");
    }//GEN-LAST:event_jtfTIMKIEMMouseClicked

    private void jcbTIMKIEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIMKIEMActionPerformed
        if (jcbTIMKIEM.getSelectedItem().equals("Địa Chỉ và Ngày Sinh")) {
            jtfTIMKIEMNANGCAO.setEnabled(true);
        } else {
            jtfTIMKIEM.setText("Nhập dữ liệu tìm kiếm");
            jtfTIMKIEMNANGCAO.setText("Nhập dữ liệu tìm kiếm");
            jtfTIMKIEMNANGCAO.setEnabled(false);
        }
    }//GEN-LAST:event_jcbTIMKIEMActionPerformed

    private void jtfTIMKIEMNANGCAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfTIMKIEMNANGCAOMouseClicked
        jtfTIMKIEMNANGCAO.setText("");
    }//GEN-LAST:event_jtfTIMKIEMNANGCAOMouseClicked

    private void jtbNHANVIENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbNHANVIENMouseClicked
        if (evt.getSource() == jtbNHANVIEN) {
            int i = jtbNHANVIEN.getSelectedRow();
            if (i >= 0) {
                NHANVIEN nv = new NHANVIEN();
                nv = NhanVienBUS.NHANVIENLIST.get(i);
                jtfMANV.setText(nv.getMaNV());
                jtfTENNV.setText(nv.getTenNV());
                jtfSDT_NV.setText(nv.getSDT_NV());
                jtfNGAYSINH_NV.setText(nv.getNgaySinh_NV());
                jtfDIACHI_NV.setText(nv.getDiaChi_NV());
            }
        }
    }//GEN-LAST:event_jtbNHANVIENMouseClicked

    private void btnXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXUATActionPerformed
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("Nhân Viên");

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH NHÂN VIÊN");

            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Họ và tên");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày sinh");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Giới tính");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Số điện thoại");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Địa chỉ");

           

            List<NHANVIEN> NHANVIENLIST = NhanVienBUS.NHANVIENLIST;

            for (int i = 0; i < NHANVIENLIST.size(); i++) {
                NHANVIEN nv = NHANVIENLIST.get(i);
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(nv.getMaNV());
                row.createCell(2).setCellValue(nv.getTenNV());
                row.createCell(3).setCellValue(nv.getSDT_NV());
                row.createCell(4).setCellValue(nv.getNgaySinh_NV());
                row.createCell(5).setCellValue(nv.getDiaChi_NV());
            }

            FileOutputStream out = new FileOutputStream(new File("C:\\Users\\Quang Long\\Dropbox\\PC\\Documents\\NetBeansProjects\\QL_CUA_HANG_QUAN_AO\\src\\Excel\\QUANLI.xlsx"));
            workbook.write(out);
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXUATActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRESET;
    private javax.swing.JButton btnSUA;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btnTIMKIEM;
    private javax.swing.JButton btnXOA;
    public javax.swing.JButton btnXUAT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbTIMKIEM;
    private javax.swing.JPanel jpnView;
    public static javax.swing.JTable jtbNHANVIEN;
    private javax.swing.JTextField jtfDIACHI_NV;
    public static javax.swing.JTextField jtfMANV;
    private javax.swing.JTextField jtfNGAYSINH_NV;
    private javax.swing.JTextField jtfSDT_NV;
    private javax.swing.JTextField jtfTENNV;
    private javax.swing.JTextField jtfTIMKIEM;
    private javax.swing.JTextField jtfTIMKIEMNANGCAO;
    // End of variables declaration//GEN-END:variables
}
