/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import BUS.HoaDonBUS;
import BUS.KhachHangBUS;
import BUS.NhanVienBUS;
import BUS.PhieuNhapHangBUS;
import BUS.SanPhamBUS;
import BUS.ThongKeBUS;
import Bean.DanhMucBean;

import Model.HOADON;
import Model.KHACHHANG;
import Model.NHANVIEN;
import Model.PHIEUNHAPHANG;
import Model.SANPHAM;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quang Long
 */
public class THONGKE_VIEW extends javax.swing.JPanel {

    DefaultTableModel tableModel;

    /**
     * Creates new form THONGKE_VIEW
     */
    public THONGKE_VIEW() {
        initComponents();
        tableModel = (DefaultTableModel) jtbTHONGKE.getModel();

        
        
        
    }

    /* private void showTHONGKE() {
        ThongKeBUS tkBUS = new ThongKeBUS();
        ThongKeBUS.THONGKELIST = tkBUS.getAllThongKe();

        tableModel.setRowCount(0);

//        for (THONGKE tk : ThongKeBUS.THONGKELIST) {
//            Vector<String> row = new Vector<>();
//            row.add(tk.getTHOIGIAN());
//            row.add(String.valueOf(tk.getDOANHTHU()));
//            row.add(String.valueOf(tk.getTONGCONG()));
//            
//            tableModel.addRow(row);
//        }

        for(HOADON tk : ThongKeBUS.THONGKELIST){
            Vector<String> row = new Vector<>();
            row.add(tk.getNgayLapHD());
            row.add(String.valueOf(tk.getTongTien()));
        }

        jtbTHONGKE.setModel(tableModel);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbTONGNV = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbTONGKH = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlbTONGNH = new javax.swing.JLabel();
        jlbTONGDOANHTHU = new javax.swing.JLabel();
        jcbNAM = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbTONGSP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTHONGKE = new javax.swing.JTable();
        btnTHONGKE = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 900));

        jPanel1.setBackground(new java.awt.Color(255, 200, 231));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/graph (1).png"))); // NOI18N
        jLabel1.setText("THỐNG KÊ TỔNG QUÁT");

        jPanel3.setBackground(new java.awt.Color(210, 145, 188));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/networking.png"))); // NOI18N
        jLabel3.setText("NHÂN VIÊN");

        jlbTONGNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTONGNV.setText("Tổng Nhân Viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTONGNV)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jlbTONGNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(210, 145, 188));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rating.png"))); // NOI18N
        jLabel4.setText("KHÁCH HÀNG");

        jlbTONGKH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTONGKH.setText("Tổng Khách Hàng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(99, 99, 99))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jlbTONGKH)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jlbTONGKH)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(210, 145, 188));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money.png"))); // NOI18N
        jLabel5.setText("DOANH THU");

        jlbTONGNH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTONGNH.setText("Tổng sản phẩm nhập");

        jlbTONGDOANHTHU.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTONGDOANHTHU.setText("Tổng hóa đơn ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbTONGNH, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTONGDOANHTHU)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(110, 110, 110))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTONGNH)
                    .addComponent(jlbTONGDOANHTHU))
                .addContainerGap())
        );

        jcbNAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2020", "2021", "2022" }));
        jcbNAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNAMActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(210, 145, 188));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clothes-hanger.png"))); // NOI18N
        jLabel2.setText("SẢN PHẨM");

        jlbTONGSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTONGSP.setText("Tổng Sản Phẩm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jlbTONGSP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jlbTONGSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 200, 231));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/analytics.png"))); // NOI18N
        jButton1.setText("CHI TIẾT");

        jtbTHONGKE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null},
                {"2", null},
                {"3", null},
                {"4", null},
                {null, null},
                {"Tổng Doanh Thu", null},
                {null, null}
            },
            new String [] {
                "Quý", "Doanh thu"
            }
        ));
        jScrollPane2.setViewportView(jtbTHONGKE);

        btnTHONGKE.setText("THỐNG KÊ");
        btnTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHONGKEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(btnTHONGKE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbNAM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTHONGKE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHONGKEActionPerformed
        List<NHANVIEN> NV_TKLIST = new ArrayList<>();
        List<KHACHHANG> KH_TKLIST = new ArrayList<>();
        List<SANPHAM> SP_TKLIST = new ArrayList<>();
        List<PHIEUNHAPHANG> PNH_TKLIST = new ArrayList<>();
        List<HOADON> HD_TKLIST = new ArrayList<>();

        int i = 0;

        NhanVienBUS nvBUS = new NhanVienBUS();
        NV_TKLIST = nvBUS.getAllUsers();
        for (NHANVIEN nvkq : NV_TKLIST) {
            i++;
            jlbTONGNV.setText((i + 1) + " Nhân Viên");
        }

        KhachHangBUS khBUS = new KhachHangBUS();
        KH_TKLIST = khBUS.getAllUsers();
        for (KHACHHANG khkq : KH_TKLIST) {
            i++;
            jlbTONGKH.setText((i + 1) + " Khách Hàng");
        }

        SanPhamBUS spBUS = new SanPhamBUS();
        SP_TKLIST = spBUS.getAllSanPham();
        for (SANPHAM spkq : SP_TKLIST) {
            i++;
            jlbTONGSP.setText((i + 1) + " Sản Phẩm");
        }

        PhieuNhapHangBUS pnhBUS = new PhieuNhapHangBUS();
        PNH_TKLIST = pnhBUS.getAllPNH();
        for (PHIEUNHAPHANG pnhkq : PNH_TKLIST) {
            i++;
            jlbTONGNH.setText((i + 1) + " Đơn Nhập Hàng");
        }

        HoaDonBUS hdBUS = new HoaDonBUS();
        HD_TKLIST = hdBUS.getAllHD();
        for (HOADON hdkq : HD_TKLIST) {
            i++;
            jlbTONGDOANHTHU.setText((i + 1) + " Hóa Đơn");
        }
    }//GEN-LAST:event_btnTHONGKEActionPerformed

    private void jcbNAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNAMActionPerformed
        /*if (jcbNAM.getSelectedItem().equals(0)) {
            ThongKeDAO tkDAO = new ThongKeDAO();
            tkDAO.getAllThongKeQuy1();
        } else {
            ThongKeDAO tkDAO = new ThongKeDAO();
            tkDAO.getAllThongKeQuy1();
        }*/
        
        int i = jcbNAM.getSelectedIndex();
        ThongKeBUS tkBUS = new ThongKeBUS();
        double DoanhThuQuy1 = tkBUS.getAllThongKeQuy1(i);
        //System.out.println(DoanhThuQuy1);
        
        double DoanhThuQuy2 = tkBUS.getAllThongKeQuy2(i);
        //System.out.println(DoanhThuQuy2);
        
        double DoanhThuQuy3 = tkBUS.getAllThongKeQuy3(i);
        //System.out.println(DoanhThuQuy3);
        
        double DoanhThuQuy4 = tkBUS.getAllThongKeQuy4(i);
        //System.out.println(DoanhThuQuy4);
        
        Double Tongdanhthu = DoanhThuQuy1 + DoanhThuQuy2 + DoanhThuQuy3 +DoanhThuQuy4;
        
        tableModel.setValueAt(DoanhThuQuy1, 0, 1);
        tableModel.setValueAt(DoanhThuQuy2, 1, 1);
        tableModel.setValueAt(DoanhThuQuy3, 2, 1);
        tableModel.setValueAt(DoanhThuQuy4, 3, 1);
        tableModel.setValueAt(Tongdanhthu, 5, 1);
    }//GEN-LAST:event_jcbNAMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTHONGKE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JComboBox<String> jcbNAM;
    private javax.swing.JLabel jlbTONGDOANHTHU;
    private javax.swing.JLabel jlbTONGKH;
    private javax.swing.JLabel jlbTONGNH;
    private javax.swing.JLabel jlbTONGNV;
    private javax.swing.JLabel jlbTONGSP;
    private javax.swing.JTable jtbTHONGKE;
    // End of variables declaration//GEN-END:variables
}
